[workspace]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "binsparse-specification"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
render = "bikeshed spec spec/latest/index.bs"

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
bikeshed = ">=5.1.2, <6"
