name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Output to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1
        with:
          source: spec/latest/index.bs

      - name: Publish HTML to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
